### ISSUE TITLE
Could JSLK still fit on a floppy?

### ISSUE THREAD

**Issue by informer2016** [sofferjacob/jslk#18]
I have noticed "Floppy Images are now obsolete" note at your Makefile. But why? Even today the floppies are still being used, for example - as virtual floppies inside the coreboot open source BIOS. Just imagine: your wonderful OS could be a part of someone's BIOS build! _(for coreboot supported motherboard, maybe you have or could get one - see https://www.coreboot.org/Supported_Motherboards )_

If you already have a coreboot-supported motherboard, or a real chance to get one, - wouldn't it be cool to be able to launch your own OS straight from the BIOS chip? ;) With one simple command its possible to add any floppy to coreboot BIOS build - and then you see it as a boot entry! Multiple floppies could be added this way _(as long as you have enough space left inside the BIOS flash chip, luckily LZMA compression could be used for the stored floppies to reduce their occupied size)_

**Comment by sofferjacob** [comment]
Hi @informer2016 
JSLK can still fit into a floppy perfectly, I just changed the install and distribution medium to an ISO image because it is a newer, more supported and overall easier to use, build and install than floppy images. 
In summary, if you want to build it as a floppy image you can copy the binary built using make to a floppy disk or you can do the following:
1. Uncomment the floppy option (or rename and uncomment the old image option, depending on the platform you are using) from the Makefile.
2. Download an older release (I think 0.0.7pa should do the trick) and copy `system.img` to the newer release working directory or build one yourself and name it system.img .
3. Run `make TARGET=x86common clean all floppy`
4. You now have the latest JSLK kernel in a floppy.
Anyways, in a few weeks I will post the `system.img` floppy image to the release page to make it easier for everyone to do, add these instructions to the README.md and uncomment the `floppy`option from the Makefile in the next release.

PS: I found this old `system.img` in an old branch I had cloned to my computer. I will leave it attached, but still,  I recommend using the one from 0.0.7pa. And cool project (the BIOS one)

**Comment by sofferjacob** [comment]
For now I am going to close this issue

**Comment by informer2016** [comment]
@sofferjacob Thank you very much for your floppy instructions! I would try following them soon
